@startuml
!include_many ../data-lab-style.txt
!include_many model-activities.puml

title: An idealised  view of\na research data cycle with\nArchival Repository Infrastructure



rectangle "Research & Data Management Activities" as activities <<workspace>> {



}


 database "Archival Repositories" as repo <<repository>> {
 
}

actor "Keep" as keep    
keep -> repo 

cur ---> repo :  Deposit
repo --> coll : Reuse
@enduml

