

@startuml

!include ./data-lab-style.md

title: Potential Future Community Data Lab Architecture
top to bottom direction

rectangle "Entry web site" <<guidance>> as web {
    rectangle "Tools Search" as ts {

    }
    rectangle "Curated Links" as cl {
        
    }
     rectangle "Tools" <<index>> {

    }

}

rectangle "Research and Data Guides" <<guidance>> as dgs {


   
 }



cl -down-> dgs 

rectangle "Infrastructure" {


database "Data Repositories & Indices" as repos <<repository>> {
    rectangle "Research-ready" {
   
    database "LDaCA/ATAP"    {

    }
    database "ADA"   {

    }
    database "HASS\nResearch Data\nrepository" as hr {

    }
    database "Zeondo et al" {

    }
    }
    rectangle "Public GLAM" {
     database "Trove"   {

    }
    database "..." as dn   {

    }
    database "1" as a1   {

    }
     database "2"  as a2   {

    }
    }
    
}

rectangle "Compute" {
    rectangle "Compute Services" as Services  <<workspace>>  {
    rectangle "AWS"
    rectangle "Azure"
    rectangle "Acme University"
    rectangle "..." as cn
    rectangle "Nectar"
    }
}

rectangle "Analytical Workpaces" as aws {
    rectangle "On Demand\nAwoken from being 'at rest'" as od  <<workspace>>  {
       rectangle "Notebook instances"
       rectangle "Virtual Desktop Sessions"
       rectangle "Ephemeral APIs"


    }
    rectangle "Fixed Term"  as lr  <<workspace>>  {
        rectangle "Stylometry"
        rectangle "..." as apps

    }


    lr -down--> Services
    od --down--> Services

}


rectangle "Annotation & Node Graph workspaces" as aw {
    rectangle "On Demand" as odann  <<workspace>>  {
       rectangle "RO-Crate editor"


    }
    rectangle "Fixed Term"  as lrann  <<workspace>>  {
        rectangle "Image Annotation\nWorkbench"
        rectangle "Omeka(S)"
        rectangle "POTENTIAL: RO-Crate Collection App"
        rectangle "..." as apps

    }

}
}



Tools -> dgs : Index guides
Compute ---down---> repos 
Trove <-down- a1
Trove <-down- a2
dgs --down--> aws : Recommmend / guide
dgs -down-> aw : Embed
@enduml
