
@startuml
!include_many ./data-lab-style.md
title: Story: 'CDLifying' a desktop or web app

start
note right
Assumption: this app is being considered for CDL investment
Because it has become hard to sustain or distribute
end note

switch (Separate: \nAnalytical components from\ncollecting/storage components)

case (Data storage\n- choose compliant repo/cms solution)
partition #springgreen Repository  {
  switch (Access / scale)

    case (Compliant domain-specific\nrepo/app exists)
        :Use it;
    case (Small-medium OA)
        :Use generic repo\n(eg) Omeka S;
    case (Large/complex or\nSensitive)
        :Use RRkive;
        note left
            --------
            OUT OF SCOPE??
            --------
        end note
  endswitch
  :Data preservable in RO-Crate;
}
case (Analytics)
partition #FFC7D8 Workspace {
    :Find 'Intellectual core';
    if (Libraries exist) then (yes)

    else (no)
        :Write new library(s);
        note left 
            If possible, 
            extend an an 
            existing package 
            (eg NLTK)
        end note
    endif
    :One or more:\n- Notebook\n- Repo plugin\n- Static deployment\n- Deployable Container;
}
endswitch




stop
@enduml