@startuml
!include ./data-lab-style.md
title: Transforming Proxy

[Spreadsheet] <<workspace>>
[Voyant] <<workspace>>
[TEIPublisher] <<workspace>>
[Feed Reader\napp] as FeedReader <<workspace>>
[WordPress] <<workspace>>
[Custom Trove XML app] as TroveXMLClient <<workspace>>

component TroveProxy {
  port tei
  port csv
  port atom
  port trovexml

  component [TEI transform] as TEItransform
  component [CSV transform] as CSVtransform
  component [Atom transform] as Atomtransform

  component GenericProxy
}

Component TroveAPI {
}


Voyant <--> tei
TEIPublisher <--> tei
tei <--> TEItransform
TEItransform <--> GenericProxy 

WordPress <--> atom
FeedReader <--> atom
atom <--> Atomtransform
Atomtransform <--> GenericProxy

Spreadsheet <--> csv
csv <--> CSVtransform
CSVtransform <--> GenericProxy

TroveXMLClient <--> trovexml
trovexml <--> GenericProxy

GenericProxy <--down--> TroveAPI

@enduml
