@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include_many ../data-lab-style.txt
!include c4-style.txt

HIDE_STEREOTYPE()

LAYOUT_TOP_DOWN()

Boundary(infra, "Infrastructure classified by Use Case", "Infrastructure", $tags="infra-main") {
   System_Boundary(admin, "Administrative Systems", "Admin", $tags="infra-admin") {
      Boundary(cris, "Current Research Information Systems (CRIS)", "Admin", $tags="infra-admin") {
         Container(grants, "Grants & Financial", "Administrative system", $tags="infra-admin")
         Container(ethics, "Ethics", "Administrative system", $tags="infra-admin")
         Container(metrics, "Research Metrics", "Administrative system", $tags="infra-admin")
      }
      Container(dmp, "Data Management Planning", "Administrative system", $tags="infra-admin")
      Container(rights, "Licence and Rights\nManagement", "Administrative system", $tags="infra-admin")
      Container(auth, "Authentication & Authorization", "Administrative system", $tags="infra-admin")
   }

   System_Boundary(repo, "Archival Repositories", "Repository", $tags="infra-repository") {
      Container(ja, "Journals, books & other publications", "Repository", $tags="infra-repository")
      Container(glam, "GLAM systems", "Repository", $tags="infra-repository")
      Container(irs, "Institutional Research\nRepositories", "Repository", $tags="infra-repository")
      Container(domain_repo, "Domain Repositories", "Repository", $tags="infra-repository")
      Container(pub, "Public Repositories", "Repository", $tags="infra-repository")
      Container(lib, "Libraries", "Repository", $tags="infra-repository")
   }

   System_Boundary(ws, "Workspaces", "Workspace", $tags="infra-workspace") {
      Container(new_data, "Novel /\nnon-archive\ndata", "Workspace source", $tags="infra-workspace")
      ContainerDb(risk, "At-risk needs-to-be-archived\ndata in working storage", "Workspace storage", $tags="infra-workspace")
      Container(comp, "Computing Environments", "Workspace tool", $tags="infra-workspace")
      Container(survey, "Survey tools", "Workspace tool", $tags="infra-workspace")
      Container(eln, "Electronic Lab Notebooks", "Workspace tool", $tags="infra-workspace")
      Container(other, "Other research tools", "Workspace tool", $tags="infra-workspace")
   }
}

@enduml
