@startuml
!include_many ../data-lab-style.txt
!include_many model-activities.puml








rectangle "Infrastructure" as infra {
 rectangle "Administrative Systems" <<admin>> as admin
 
 database "Archival Repositories" as repo <<repository>> {
 }
 rectangle "Workspaces" <<workspace>> as ws {
      database "Working storage" as risk
      cloud "Applications, tools &\ncomputing environments" as comp
 }
 
}

cloud "Novel /\nnon-archive\ndata" as new 


note bottom of risk: -Unmanaged/\nnon-secure assets\n-Newly created data\n-Data in use

an <-[thickness=10]-> comp : Use
prep <-[thickness=5]-> comp : Use
plan -[thickness=5]-> admin : Use
new --right--> coll : Import data from external sources
risk <--up--> coll : Store / use\nin-progress data
repo --up--> coll : Re-use
dep --down-> repo  : Archive


@enduml

