@startuml

!include ../data-lab-style.txt
title: Research Data Activities  

top to bottom direction

rectangle "Research & Data Management Activities" as activities <<workspace>> {

actor "Collect" as coll
actor "Prepare" as prep 
actor "Keep" as dep
actor "Analyse"  as an

}


coll -down-> prep : Describe 
prep -down-> dep : Publish / Deposit
prep -right-> an : Use
an -left-> coll : New


@enduml