@startuml
!include_many ../data-lab-style.txt
!include_many model-activities.puml

title: HASS Research Data Reference Model



cloud "Novel /\nnon-archive\ndata" as new 

note left of new: Unmanaged/\nnon-secure assets
note right of new: Newly created data\nsurveys, obeservations etc




 database "Archival Repositories" as repo <<repository>> {
 rectangle "Libraries"
 rectangle "Research Data Repositories" {
    rectangle "Institutional"
    rectangle "Discipline"
    rectangle "Publisher"
    rectangle "International"
 }
 rectangle "GLAM Holdings"

 }   

new <--down-- coll : Find / Discover / Elict
repo <--up-- coll : Reuse
dep --down-> repo : Deposit

@enduml

