@startuml

!include ../data-lab-style.txt

top to bottom direction

rectangle "Activities" as activities  {
    actor "Plan" <<admin>> as plan
    actor "Collect" <<workspace>> as coll
    actor "Process/\nDescribe" <<workspace>> as prep 
    actor "Deposit/\nPublish" <<repository>> as dep
    actor "Analyse"  <<workspace>> as an

}




@enduml