@startuml
!include_many ../data-lab-style.txt
!include_many model-activities.puml

title: Activities in Infrastructure Context (2)




rectangle "Storage Infrastucture" as infrastructure {

rectangle "Access and authentication services" {

 database "Archival Repositories" as repo <<repository>> {

 }   

  database "Workspaces" as comp <<workspace>> {
    
 }   
note bottom of comp
Collections eg websites
Working data
Bibliographies
Code
Desktop computation
...
end note
}
}

repo --up--> coll : Reuse
cur --down-> repo : Deposit
an -down-> repo : Publish /\nArchive Results
an  --down--> comp : Use,\nextend
cur <--down-- comp : Preserve
@enduml

