@startuml

!include ../data-lab-style.txt
title: Research Data Activities  

top to bottom direction

rectangle "Research & Data Management Activities" as activities <<workspace>> {

actor "Collect" as coll
actor "Prepare" as prep 
actor "Deposit" as dep
actor "Analyse"  as an

}


coll -right-> prep
prep -down-> dep
prep <-right-> an
an -down-> dep


@enduml